server:
  port: 8189
  servlet:
    context-path: /video-service
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE_URI}/postgres
    username: postgres
    password: postgrespass
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
    open-in-view: false